development:
  adapter: postgresql
  encoding: unicode
  database: spree_development
  pool: 5
  username: spree
  password: spree
test:
  adapter: postgresql
  encoding: unicode
  database: spree_test
  pool: 5
  username: spree
  password: spree
production:
  adapter: postgresql
  encoding: unicode
  database: spree_production
  pool: 5
  username: spree
  password: spree
